name: Run Pytest with Coverage

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - '**.py'          # Только Python файлы
      - '!**.md'         # Игнорировать любые Markdown файлы
  pull_request:
    branches-ignore:
      - main
    paths:
      - '**.py'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # или твоя версия

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=term-missing --cov-report=html --disable-warnings -v

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/
